<a href="https://colab.research.google.com/github/pras5449/-Assignment-Task-6/blob/main/Boston_housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy library would be required, so code begins by importing it**

In [ ]:
import numpy as np

**Import phi and phi_test from train and test datasets using NumPy's loadtxt function**

In [ ]:
phi = np.loadtxt('/content/train.csv', dtype='float', delimiter=',', skiprows=1, usecols=list(range(1, 14)))
phi_tst = np.loadtxt('/content/test.csv', dtype='float', delimiter=',',skiprows=1, usecols=list(range(1, 14)))

array([4.5440e-02, 0.0000e+00, 3.2400e+00, 0.0000e+00, 4.6000e-01,
       6.1440e+00, 3.2200e+01, 5.8736e+00, 4.0000e+00, 4.3000e+02,
       1.6900e+01, 3.6857e+02, 9.0900e+00])

**Import y from train dataset using the loadtxt function**

In [ ]:
y = np.loadtxt('/content/train.csv', dtype='float', delimiter=',', skiprows=1, usecols=14, ndmin=2)

**Concatenate coloumn of 1s to right of phi and phi_test**

In [ ]:
phi_tst = np.concatenate((phi_tst, np.ones((105, 1))), axis=1)
phi = np.concatenate((phi, np.ones((400, 1))), axis=1)

**Apply min max scaling on each coloumn of phi and phi_test**

In [ ]:
for i in range(0, 13):
    cl_mx = max(phi[:, i])
    cl_mn = min(phi[:, i])
    phi[:, i] = (phi[:, i] - cl_mn) / (cl_mx - cl_mn)
    phi_tst[:, i] = (phi_tst[:, i] - cl_mn) / (cl_mx - cl_mn)

**Apply log scaling on y**

In [ ]:
y = np.log(y) # Taking log for y values

**Define a function to calculate change in error function based on phi, w and p norm**

In [ ]:
w = np.zeros((14, 1))
w

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
phi

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, ..., 3.06380e+02,
        1.72800e+01, 1.00000e+00],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, ..., 3.96330e+02,
        6.21000e+00, 1.00000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, ..., 3.63430e+02,
        4.59000e+00, 1.00000e+00],
       ...,
       [6.65492e+00, 0.00000e+00, 1.81000e+01, ..., 3.96900e+02,
        1.39900e+01, 1.00000e+00],
       [1.31170e-01, 0.00000e+00, 8.56000e+00, ..., 3.87690e+02,
        1.40900e+01, 1.00000e+00],
       [6.46600e-02, 7.00000e+01, 2.24000e+00, ..., 3.68240e+02,
        4.97000e+00, 1.00000e+00]])

In [ ]:
np.transpose(phi)

array([[9.55770e-01, 2.87500e-02, 1.22358e+00, ..., 6.65492e+00,
        1.31170e-01, 6.46600e-02],
       [0.00000e+00, 2.80000e+01, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 7.00000e+01],
       [8.14000e+00, 1.50400e+01, 1.95800e+01, ..., 1.81000e+01,
        8.56000e+00, 2.24000e+00],
       ...,
       [3.06380e+02, 3.96330e+02, 3.63430e+02, ..., 3.96900e+02,
        3.87690e+02, 3.68240e+02],
       [1.72800e+01, 6.21000e+00, 4.59000e+00, ..., 1.39900e+01,
        1.40900e+01, 4.97000e+00],
       [1.00000e+00, 1.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        1.00000e+00, 1.00000e+00]])

In [ ]:
np.dot(np.transpose(phi), phi)

array([[3.90920096e+04, 3.68717740e+02, 2.66920393e+04, 5.14898800e+01,
        1.00911724e+03, 8.92229686e+03, 1.38969707e+05, 2.80865885e+03,
        3.38507209e+04, 9.64771585e+05, 2.99777625e+04, 4.26921496e+05,
        3.06956108e+04, 1.50287637e+03],
       [3.68717740e+02, 2.55484500e+05, 1.54612550e+04, 2.30000000e+02,
        1.90301675e+03, 2.94834425e+04, 1.55663850e+05, 2.95602334e+04,
        1.77315000e+04, 1.30857750e+06, 7.37693500e+04, 1.70470885e+06,
        2.92295250e+04, 4.38800000e+03],
       [2.66920393e+04, 1.54612550e+04, 6.65535331e+04, 3.70580000e+02,
        2.65788291e+03, 2.67556893e+04, 3.46847031e+05, 1.26578360e+04,
        5.58288000e+04, 2.10559357e+06, 8.29241190e+04, 1.49235971e+06,
        6.77147176e+04, 4.37457000e+03],
       [5.14898800e+01, 2.30000000e+02, 3.70580000e+02, 2.90000000e+01,
        1.70369000e+01, 1.89185000e+02, 2.21950000e+03, 8.82278000e+01,
        2.53000000e+02, 1.09160000e+04, 5.04700000e+02, 1.07901900e+04,
        3.260